### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by kilinkis** [justinwhall/wordpress-gatsby-preview-starter#11]
hi Justin,

I tried to start using this repo again after abandoning the project for a few weeks and it wasn't working anymore for some weird reason. All the single views of posts were just returning a blank screen.

Since I only had edited two files, I decided to `rm -rf` and start again.

so after cloning, I see the step on the quick start that says:

`Rename theme/sample.env > .env & enter creds. Hint: current creds will`

hmm, what credentials am I supposed to use? where am I supposed to look for them?
I can't remember how I solved this last time.
Also, that message says `Hint: current creds will`, did you mean "NOT work"? because they aren't 😅when trying to up de docker image, I see credentials errors.

thanks

**Comment by justinwhall** [comment]
The `.env` holds the credentials for WP. They should work to log you in here: http://localhost:8000/wp-admin

Hard to say what's going on with the given information but it sounds like WordPress isn't running at all?

**Comment by kilinkis** [comment]
You're right, I think I messed up with the docker, now it works fine.
